server:
  port: 8082

spring:
  rabbitmq:
    host: localhost
#    virtual-host: /
    # amqp协议端口号:5672; 集群端口号:25672;http端口号:15672;
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true

#    listener:
#      simple:
#        retry:
#          # broker未收到确认消息，是否再次向消费者投递消息（默认：false）
#          enabled: true
#          max-attempts: 6
#          # 投递的间隔（单位：ms）
#          initial-interval: 2000

